export type StockSuggestion = { symbol: string; name: string };

export type StockCategory = {
  id: string;
  name: string;
  description: string;
  icon: string;
  stocks: StockSuggestion[];
};

export const STOCK_CATEGORIES: StockCategory[] = [
  {
    id: "banking",
    name: "Banking & Finance",
    description: "Banks, payments, and asset managers",
    icon: "🏦",
    stocks: [
      { symbol: "JPM", name: "JPMorgan Chase" },
      { symbol: "BAC", name: "Bank of America" },
      { symbol: "WFC", name: "Wells Fargo" },
      { symbol: "GS", name: "Goldman Sachs" },
      { symbol: "MS", name: "Morgan Stanley" },
      { symbol: "V", name: "Visa" },
      { symbol: "MA", name: "Mastercard" },
      { symbol: "AXP", name: "American Express" },
      { symbol: "BLK", name: "BlackRock" },
      { symbol: "SCHW", name: "Charles Schwab" },
      { symbol: "BRK.B", name: "Berkshire Hathaway" },
      { symbol: "C", name: "Citigroup" },
    ],
  },
  {
    id: "it-software",
    name: "IT & Software",
    description: "Software, cloud, and internet platforms",
    icon: "💻",
    stocks: [
      { symbol: "AAPL", name: "Apple" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "META", name: "Meta Platforms" },
      { symbol: "ORCL", name: "Oracle" },
      { symbol: "CRM", name: "Salesforce" },
      { symbol: "ADBE", name: "Adobe" },
      { symbol: "NOW", name: "ServiceNow" },
      { symbol: "INTU", name: "Intuit" },
      { symbol: "SNOW", name: "Snowflake" },
      { symbol: "PLTR", name: "Palantir" },
      { symbol: "UBER", name: "Uber" },
    ],
  },
  {
    id: "semiconductors",
    name: "Semiconductors",
    description: "Chips, GPUs, and semiconductor equipment",
    icon: "🔌",
    stocks: [
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "AMD", name: "AMD" },
      { symbol: "INTC", name: "Intel" },
      { symbol: "AVGO", name: "Broadcom" },
      { symbol: "QCOM", name: "Qualcomm" },
      { symbol: "TXN", name: "Texas Instruments" },
      { symbol: "MU", name: "Micron" },
      { symbol: "AMAT", name: "Applied Materials" },
      { symbol: "LRCX", name: "Lam Research" },
      { symbol: "ASML", name: "ASML" },
      { symbol: "TSM", name: "TSMC" },
      { symbol: "ARM", name: "Arm Holdings" },
    ],
  },
  {
    id: "pharma",
    name: "Pharmaceuticals",
    description: "Drug makers and biotech leaders",
    icon: "💊",
    stocks: [
      { symbol: "JNJ", name: "Johnson & Johnson" },
      { symbol: "LLY", name: "Eli Lilly" },
      { symbol: "MRK", name: "Merck" },
      { symbol: "PFE", name: "Pfizer" },
      { symbol: "ABBV", name: "AbbVie" },
      { symbol: "BMY", name: "Bristol-Myers Squibb" },
      { symbol: "AMGN", name: "Amgen" },
      { symbol: "GILD", name: "Gilead Sciences" },
      { symbol: "REGN", name: "Regeneron" },
      { symbol: "VRTX", name: "Vertex Pharma" },
      { symbol: "BIIB", name: "Biogen" },
      { symbol: "MRNA", name: "Moderna" },
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare Services",
    description: "Hospitals, insurers, and medical devices",
    icon: "🏥",
    stocks: [
      { symbol: "UNH", name: "UnitedHealth" },
      { symbol: "CVS", name: "CVS Health" },
      { symbol: "ELV", name: "Elevance Health" },
      { symbol: "CI", name: "Cigna" },
      { symbol: "HUM", name: "Humana" },
      { symbol: "ISRG", name: "Intuitive Surgical" },
      { symbol: "SYK", name: "Stryker" },
      { symbol: "MDT", name: "Medtronic" },
      { symbol: "ABT", name: "Abbott Labs" },
      { symbol: "TMO", name: "Thermo Fisher" },
      { symbol: "DHR", name: "Danaher" },
      { symbol: "BSX", name: "Boston Scientific" },
    ],
  },
  {
    id: "automobiles",
    name: "Automobiles",
    description: "Car makers, EVs, and auto parts",
    icon: "🚗",
    stocks: [
      { symbol: "TSLA", name: "Tesla" },
      { symbol: "TM", name: "Toyota" },
      { symbol: "F", name: "Ford" },
      { symbol: "GM", name: "General Motors" },
      { symbol: "RIVN", name: "Rivian" },
      { symbol: "LCID", name: "Lucid Motors" },
      { symbol: "STLA", name: "Stellantis" },
      { symbol: "HMC", name: "Honda" },
      { symbol: "APTV", name: "Aptiv" },
      { symbol: "BWA", name: "BorgWarner" },
      { symbol: "ALV", name: "Autoliv" },
      { symbol: "MBLY", name: "Mobileye" },
    ],
  },
  {
    id: "fmcg",
    name: "FMCG & Consumer",
    description: "Food, beverages, and household brands",
    icon: "🛒",
    stocks: [
      { symbol: "PG", name: "Procter & Gamble" },
      { symbol: "KO", name: "Coca-Cola" },
      { symbol: "PEP", name: "PepsiCo" },
      { symbol: "WMT", name: "Walmart" },
      { symbol: "COST", name: "Costco" },
      { symbol: "MDLZ", name: "Mondelez" },
      { symbol: "KHC", name: "Kraft Heinz" },
      { symbol: "CL", name: "Colgate-Palmolive" },
      { symbol: "KMB", name: "Kimberly-Clark" },
      { symbol: "GIS", name: "General Mills" },
      { symbol: "HSY", name: "Hershey" },
      { symbol: "MNST", name: "Monster Beverage" },
    ],
  },
  {
    id: "retail",
    name: "Retail & E-commerce",
    description: "Online and offline retail leaders",
    icon: "🛍️",
    stocks: [
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "HD", name: "Home Depot" },
      { symbol: "LOW", name: "Lowe's" },
      { symbol: "TGT", name: "Target" },
      { symbol: "NKE", name: "Nike" },
      { symbol: "SBUX", name: "Starbucks" },
      { symbol: "MCD", name: "McDonald's" },
      { symbol: "BKNG", name: "Booking Holdings" },
      { symbol: "ABNB", name: "Airbnb" },
      { symbol: "EBAY", name: "eBay" },
      { symbol: "ETSY", name: "Etsy" },
      { symbol: "ROST", name: "Ross Stores" },
    ],
  },
  {
    id: "energy",
    name: "Oil & Gas",
    description: "Exploration, refining, and oilfield services",
    icon: "🛢️",
    stocks: [
      { symbol: "XOM", name: "Exxon Mobil" },
      { symbol: "CVX", name: "Chevron" },
      { symbol: "COP", name: "ConocoPhillips" },
      { symbol: "SLB", name: "Schlumberger" },
      { symbol: "EOG", name: "EOG Resources" },
      { symbol: "MPC", name: "Marathon Petroleum" },
      { symbol: "PSX", name: "Phillips 66" },
      { symbol: "VLO", name: "Valero Energy" },
      { symbol: "OXY", name: "Occidental Petroleum" },
      { symbol: "HAL", name: "Halliburton" },
      { symbol: "BKR", name: "Baker Hughes" },
      { symbol: "DVN", name: "Devon Energy" },
    ],
  },
  {
    id: "clean-energy",
    name: "Clean Energy",
    description: "Solar, wind, and EV infrastructure",
    icon: "⚡",
    stocks: [
      { symbol: "NEE", name: "NextEra Energy" },
      { symbol: "ENPH", name: "Enphase Energy" },
      { symbol: "SEDG", name: "SolarEdge" },
      { symbol: "FSLR", name: "First Solar" },
      { symbol: "RUN", name: "Sunrun" },
      { symbol: "PLUG", name: "Plug Power" },
      { symbol: "BE", name: "Bloom Energy" },
      { symbol: "CEG", name: "Constellation Energy" },
      { symbol: "VST", name: "Vistra" },
      { symbol: "ON", name: "ON Semiconductor" },
      { symbol: "CHPT", name: "ChargePoint" },
      { symbol: "BLNK", name: "Blink Charging" },
    ],
  },
  {
    id: "metals",
    name: "Metals & Mining",
    description: "Steel, copper, gold, and industrial metals",
    icon: "⛏️",
    stocks: [
      { symbol: "NEM", name: "Newmont" },
      { symbol: "FCX", name: "Freeport-McMoRan" },
      { symbol: "NUE", name: "Nucor" },
      { symbol: "STLD", name: "Steel Dynamics" },
      { symbol: "CLF", name: "Cleveland-Cliffs" },
      { symbol: "AA", name: "Alcoa" },
      { symbol: "VALE", name: "Vale" },
      { symbol: "RIO", name: "Rio Tinto" },
      { symbol: "BHP", name: "BHP Group" },
      { symbol: "GOLD", name: "Barrick Gold" },
      { symbol: "X", name: "US Steel" },
      { symbol: "MP", name: "MP Materials" },
    ],
  },
  {
    id: "manufacturing",
    name: "Manufacturing & Industrial",
    description: "Heavy machinery, aerospace, and industrials",
    icon: "🏭",
    stocks: [
      { symbol: "CAT", name: "Caterpillar" },
      { symbol: "GE", name: "GE Aerospace" },
      { symbol: "HON", name: "Honeywell" },
      { symbol: "MMM", name: "3M" },
      { symbol: "DE", name: "Deere & Co" },
      { symbol: "BA", name: "Boeing" },
      { symbol: "RTX", name: "RTX Corp" },
      { symbol: "LMT", name: "Lockheed Martin" },
      { symbol: "NOC", name: "Northrop Grumman" },
      { symbol: "GD", name: "General Dynamics" },
      { symbol: "EMR", name: "Emerson Electric" },
      { symbol: "ITW", name: "Illinois Tool Works" },
    ],
  },
  {
    id: "telecom",
    name: "Telecom & Media",
    description: "Wireless, cable, and entertainment",
    icon: "📡",
    stocks: [
      { symbol: "T", name: "AT&T" },
      { symbol: "VZ", name: "Verizon" },
      { symbol: "TMUS", name: "T-Mobile" },
      { symbol: "CMCSA", name: "Comcast" },
      { symbol: "CHTR", name: "Charter Communications" },
      { symbol: "DIS", name: "Walt Disney" },
      { symbol: "NFLX", name: "Netflix" },
      { symbol: "WBD", name: "Warner Bros Discovery" },
      { symbol: "PARA", name: "Paramount Global" },
      { symbol: "SPOT", name: "Spotify" },
      { symbol: "EA", name: "Electronic Arts" },
      { symbol: "TTWO", name: "Take-Two Interactive" },
    ],
  },
  {
    id: "realestate",
    name: "Real Estate & REITs",
    description: "Property trusts and real estate developers",
    icon: "🏢",
    stocks: [
      { symbol: "AMT", name: "American Tower" },
      { symbol: "PLD", name: "Prologis" },
      { symbol: "EQIX", name: "Equinix" },
      { symbol: "SPG", name: "Simon Property" },
      { symbol: "O", name: "Realty Income" },
      { symbol: "PSA", name: "Public Storage" },
      { symbol: "WELL", name: "Welltower" },
      { symbol: "DLR", name: "Digital Realty" },
      { symbol: "AVB", name: "AvalonBay" },
      { symbol: "VICI", name: "VICI Properties" },
      { symbol: "EXR", name: "Extra Space Storage" },
      { symbol: "CBRE", name: "CBRE Group" },
    ],
  },
  {
    id: "insurance",
    name: "Insurance",
    description: "Life, property, and specialty insurers",
    icon: "🛡️",
    stocks: [
      { symbol: "BRK.B", name: "Berkshire Hathaway" },
      { symbol: "PGR", name: "Progressive" },
      { symbol: "CB", name: "Chubb" },
      { symbol: "MET", name: "MetLife" },
      { symbol: "AIG", name: "AIG" },
      { symbol: "ALL", name: "Allstate" },
      { symbol: "TRV", name: "Travelers" },
      { symbol: "AFL", name: "Aflac" },
      { symbol: "PRU", name: "Prudential Financial" },
      { symbol: "HIG", name: "Hartford Financial" },
      { symbol: "WRB", name: "W.R. Berkley" },
      { symbol: "ACGL", name: "Arch Capital" },
    ],
  },
  {
    id: "dividend",
    name: "Dividend Stocks",
    description: "High-yield and dividend aristocrats",
    icon: "💰",
    stocks: [
      { symbol: "JNJ", name: "Johnson & Johnson" },
      { symbol: "PG", name: "Procter & Gamble" },
      { symbol: "KO", name: "Coca-Cola" },
      { symbol: "PEP", name: "PepsiCo" },
      { symbol: "MO", name: "Altria" },
      { symbol: "T", name: "AT&T" },
      { symbol: "VZ", name: "Verizon" },
      { symbol: "IBM", name: "IBM" },
      { symbol: "MMM", name: "3M" },
      { symbol: "XOM", name: "Exxon Mobil" },
      { symbol: "CVX", name: "Chevron" },
      { symbol: "O", name: "Realty Income" },
    ],
  },
  {
    id: "largecap",
    name: "Large Cap Blue Chips",
    description: "Most valuable and established US companies",
    icon: "⭐",
    stocks: [
      { symbol: "AAPL", name: "Apple" },
      { symbol: "MSFT", name: "Microsoft" },
      { symbol: "NVDA", name: "NVIDIA" },
      { symbol: "AMZN", name: "Amazon" },
      { symbol: "GOOGL", name: "Alphabet" },
      { symbol: "META", name: "Meta" },
      { symbol: "BRK.B", name: "Berkshire Hathaway" },
      { symbol: "JPM", name: "JPMorgan" },
      { symbol: "V", name: "Visa" },
      { symbol: "UNH", name: "UnitedHealth" },
      { symbol: "XOM", name: "Exxon Mobil" },
      { symbol: "LLY", name: "Eli Lilly" },
    ],
  },
  {
    id: "etfs-index",
    name: "Index ETFs",
    description: "Broad market and sector index funds",
    icon: "📊",
    stocks: [
      { symbol: "SPY", name: "S&P 500 ETF" },
      { symbol: "QQQ", name: "Nasdaq 100 ETF" },
      { symbol: "DIA", name: "Dow Jones ETF" },
      { symbol: "IWM", name: "Russell 2000 ETF" },
      { symbol: "VTI", name: "Total US Market ETF" },
      { symbol: "VOO", name: "Vanguard S&P 500" },
      { symbol: "IVV", name: "iShares S&P 500" },
      { symbol: "RSP", name: "Equal Weight S&P 500" },
      { symbol: "SCHD", name: "Dividend Equity ETF" },
      { symbol: "ARKK", name: "ARK Innovation ETF" },
      { symbol: "XLK", name: "Tech Sector ETF" },
      { symbol: "XLF", name: "Financial Sector ETF" },
    ],
  },
  {
    id: "etfs-sector",
    name: "Sector ETFs",
    description: "Thematic and sector-specific ETFs",
    icon: "📈",
    stocks: [
      { symbol: "XLE", name: "Energy ETF" },
      { symbol: "XLV", name: "Healthcare ETF" },
      { symbol: "XLI", name: "Industrial ETF" },
      { symbol: "XLY", name: "Consumer Discretionary" },
      { symbol: "XLP", name: "Consumer Staples ETF" },
      { symbol: "XLU", name: "Utilities ETF" },
      { symbol: "XLRE", name: "Real Estate ETF" },
      { symbol: "XLB", name: "Materials ETF" },
      { symbol: "SMH", name: "Semiconductor ETF" },
      { symbol: "SOXX", name: "iShares Semiconductor" },
      { symbol: "ICLN", name: "Clean Energy ETF" },
      { symbol: "ITA", name: "Aerospace & Defense ETF" },
    ],
  },
];

export function searchStocks(query: string): { category: StockCategory; stock: StockSuggestion }[] {
  const q = query.trim().toLowerCase();
  if (!q) return [];
  const results: { category: StockCategory; stock: StockSuggestion }[] = [];
  for (const cat of STOCK_CATEGORIES) {
    for (const stock of cat.stocks) {
      if (
        stock.symbol.toLowerCase().includes(q) ||
        stock.name.toLowerCase().includes(q)
      ) {
        results.push({ category: cat, stock });
      }
    }
  }
  return results.slice(0, 24);
}

export const ALL_SUGGESTED_SYMBOLS = new Set(
  STOCK_CATEGORIES.flatMap((c) => c.stocks.map((s) => s.symbol))
);
